name = "syugo-sin-new"
# main = "worker.js"
compatibility_date = "2024-09-29"
compatibility_flags = ["nodejs_compat"]

# データベース設定
[[d1_databases]]
binding = "DB"
database_name = "syugo-sin-db"
database_id = "0eee225f-f4a4-41ea-a64b-1ae31cb92138"