name = "syugo-sin-worker"
main = "cloudflare/worker.js"
compatibility_date = "2025-09-12"

# 静的ファイルは完全にCloudflare Pagesに委譲
# WorkerはAPIエンドポイントのみを処理

[vars]
ALLOW_ORIGIN = "*"

# Square API設定（本番環境用）
# 実際のデプロイ時は Cloudflare Dashboard で環境変数を設定してください
SQUARE_APPLICATION_ID = "sandbox-sq0idb-eSzFL1OkuVb004jahtDJNA"
SQUARE_ACCESS_TOKEN = "EAAAl_UqOgNBMBjJ2JSz2o5Bu26NQKVMKqFm1yxsnHLZWFBFejQQN2ZkKEiLuoPT"
SQUARE_LOCATION_ID = "LTNYEG1WCPG4X"